### ISSUE TITLE
Chapter 6: In[7] path

### ISSUE THREAD

**Issue by yyll008** [JWarmenhoven/ISLR-python#13]
X_train = pd.read_csv('Data/Hitters_X_train.csv', index_col=0)
y_train = pd.read_csv('Data/Hitters_y_train.csv', index_col=0)
X_test = pd.read_csv('Data/Hitters_X_test.csv', index_col=0)
y_test = pd.read_csv('Data/Hitters_y_test.csv', index_col=0)

**Comment by JWarmenhoven** [comment]
The lower case 'd' in the path was not a problem for me, but I changed it anyway.
Thanks.
