### ISSUE TITLE
Chapter7:df_steps_dummies.drop error

### ISSUE THREAD

**Issue by yyll008** [JWarmenhoven/ISLR-python#14]
I fix it using:

fit3 = sm.GLM(df_steps.wage, df_steps_dummies.drop([df_steps_dummies.columns[1]], axis=1)).fit()

**Comment by JWarmenhoven** [comment]
I do not understand. What error do you get? For me, the code works.
```python
fit3 = sm.GLM(df_steps.wage, df_steps_dummies.drop(df_steps_dummies.columns[1], axis=1)).fit()
```
