### ISSUE TITLE
AttributeError: module 'glmnet' has no attribute 'ElasticNet'

### ISSUE THREAD

**Issue by S-Sanaz** [JWarmenhoven/ISLR-python#16]
Hi,
I am trying to run a code same as for chapter 6 provided here:
[](http://nbviewer.jupyter.org/github/JWarmenhoven/ISL-python/blob/master/Notebooks/Chapter%206.ipynb)
When I reach the point:
In[7]:  
```
     grid = 10**np.linspace(10,-2,100)

     ridge3 = gln.ElasticNet(alpha=0, lambda_path=grid)
     ridge3.fit(X, y)

```
I get this error:

AttributeError                            Traceback (most recent call last)
<ipython-input-32-a6627d3ac967> in <module>()
      1 grid = 10**np.linspace(10,-2,100)
      2 
----> 3 ridge3 = gln.ElasticNet(alpha=0, lambda_path=grid)
      4 ridge3.fit(X, y)

AttributeError: module 'glmnet' has no attribute 'ElasticNet'

What can I do about it?

**Comment by JWarmenhoven** [comment]
What version of glmnet are you using? How did you install it?

It runs fine for me with glmnet 2.0.0 installed via `conda install -c conda-forge glmnet`.

**Comment by S-Sanaz** [comment]
I didn't exactly install it with this code because I kept getting the error:

> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - glmnet.

I would appreciate it if you help me to install it properly.

**Comment by JWarmenhoven** [comment]
On what platform do you want to install? Have you tried to install from source as indicated on https://github.com/civisanalytics/python-glmnet

**Comment by S-Sanaz** [comment]
Yes, I do follow the instructions on github.
This is what I get:

> $ conda install -c conda-forge glmnet
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - glmnet
> 
> Current channels:
> 
>   - https://conda.anaconda.org/conda-forge/linux-32
>   - https://conda.anaconda.org/conda-forge/noarch
>   - https://repo.continuum.io/pkgs/main/linux-32
>   - https://repo.continuum.io/pkgs/main/noarch
>   - https://repo.continuum.io/pkgs/free/linux-32
>   - https://repo.continuum.io/pkgs/free/noarch
>   - https://repo.continuum.io/pkgs/r/linux-32
>   - https://repo.continuum.io/pkgs/r/noarch
>   - https://repo.continuum.io/pkgs/pro/linux-32
>   - https://repo.continuum.io/pkgs/pro/noarch
>

**Comment by JWarmenhoven** [comment]
Closing this issue. Contact maintainers @ https://github.com/civisanalytics/python-glmnet in case this has not been solved.
