### ISSUE TITLE
Anyone interested in extending python code for ISLR2?

### ISSUE THREAD

**Issue by epogrebnyak** [JWarmenhoven/ISLR-python#24]
https://www.statlearning.com/resources-second-edition

**Comment by JWarmenhoven** [comment]
It seems that some comments have been deleted?
Anyway, for the moment I will not add substantial updates to this repository having to do with the second edition of the book.

**Comment by oliverangelil** [comment]
Is anyone planning to do this?
Specifically, an implementation of the Deep Learning chapter in ISLR2 in pytorch would be nice.
@JWarmenhoven would you be open to someone raising a PR to include that chapter here?

**Comment by oliverangelil** [comment]
looks like there's another repo with that uses Python for the new chapters:
https://github.com/qx0731/Sharing_ISL_python
