### ISSUE TITLE
Can't find the data 

### ISSUE THREAD

**Issue by Ross-Li** [JWarmenhoven/ISLR-python#25]
Hi, I clicked the link (http://www-bcf.usc.edu/~gareth/ISL/data.html) in the Chapter 3 Jupyter Notebook but it directed me to (http://faculty.marshall.usc.edu/gareth-james/) and I can't find the data there.

**Comment by JWarmenhoven** [comment]
Thanks for reporting! The authors probably restructured the repositories to accommodate for the second version of the book.
Datasets can now be found here: https://www.statlearning.com/resources-first-edition
I will update the link.
