### ISSUE TITLE
Chapter 7 - Moving Beyond Linearity

### ISSUE THREAD

**Issue by JWarmenhoven** [JWarmenhoven/ISLR-python#4]
- [ ] Confidence interval for Logistic Regression
- [ ] Confidence interval for step functions

**Comment by tsansom** [comment]
Did you (or anyone else) figure out how to calculate the confidence intervals for probability predictions for logistic regression (as in the right-hand panel of figure 7.1)?

**Comment by JWarmenhoven** [comment]
I think I have seen it implemented, but can frankly not remember where...

**Comment by xavierbourretsicotte** [comment]
Could a hint be on page 292 of the latest ISLR edition ? In R the code is:
```
pfit=exp(preds$fit )/(1+exp(preds$fit ))
se.bands.logit = cbind(preds$fit+2*preds$se.fit, preds$fit-2*preds$se .fit)
se.bands = exp(se.bands.logit)/(1+exp(se.bands.logit))
```

**Comment by tsansom** [comment]
@xavierbourretsicotte That was my question on SO and the answer was excellent. See my implementation [here](https://github.com/tsansom/islpy/blob/master/notebooks/Chapter%207/Chapter%207%20-%20Moving%20Beyond%20Linearity.ipynb).

**Comment by xavierbourretsicotte** [comment]
Cool- we should update the notebook on lecture 7 then! I ll have a look over the next few weeks 

Xavier
